---
- hosts: localhost
  become: true
  connection: local
  any_errors_fatal: true
  gather_facts: false

  tasks:
    - import_tasks: packages.yaml

    - name: Mark completion of a playbook
      shell: touch /tmp/ansible_done
